#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TimerAppDroid.Resource", IsApplication=true)]

namespace TimerAppDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int AlarmNotificationTextSize = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alarm_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_small = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int AddTimerButton = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int ButtonLayout = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int PauseAllButton = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int SettingsButton = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int alarmImageView = 2131230722;
			
			// aapt resource value: 0x7f080010
			public const int alarmNameLabel = 2131230736;
			
			// aapt resource value: 0x7f080001
			public const int alarmNameTextView = 2131230721;
			
			// aapt resource value: 0x7f080012
			public const int bottonButtonsLayout = 2131230738;
			
			// aapt resource value: 0x7f080003
			public const int dismissButton = 2131230723;
			
			// aapt resource value: 0x7f080011
			public const int editAlarmName = 2131230737;
			
			// aapt resource value: 0x7f08000b
			public const int hourText = 2131230731;
			
			// aapt resource value: 0x7f080015
			public const int keypadGridLayout = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int keypadLayoutRow1 = 2131230742;
			
			// aapt resource value: 0x7f08001a
			public const int keypadLayoutRow2 = 2131230746;
			
			// aapt resource value: 0x7f08001e
			public const int keypadLayoutRow3 = 2131230750;
			
			// aapt resource value: 0x7f080022
			public const int keypadLayoutRow4 = 2131230754;
			
			// aapt resource value: 0x7f08000d
			public const int minuteText = 2131230733;
			
			// aapt resource value: 0x7f080024
			public const int numPad0 = 2131230756;
			
			// aapt resource value: 0x7f080017
			public const int numPad1 = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int numPad2 = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int numPad3 = 2131230745;
			
			// aapt resource value: 0x7f08001b
			public const int numPad4 = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int numPad5 = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int numPad6 = 2131230749;
			
			// aapt resource value: 0x7f08001f
			public const int numPad7 = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int numPad8 = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int numPad9 = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int numPadDel = 2131230755;
			
			// aapt resource value: 0x7f080025
			public const int numPadNext = 2131230757;
			
			// aapt resource value: 0x7f080013
			public const int saveButton = 2131230739;
			
			// aapt resource value: 0x7f08000f
			public const int secondText = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int seperator1 = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int seperator2 = 2131230734;
			
			// aapt resource value: 0x7f080000
			public const int space1 = 2131230720;
			
			// aapt resource value: 0x7f080014
			public const int startButton = 2131230740;
			
			// aapt resource value: 0x7f08000a
			public const int timeFieldsLayout = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int timerListView = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int topLevelLayout = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlarmNotification = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TimerEditor = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int elegant_ringtone = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int AlarmDismiss = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int AlarmNameLabel = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int DefaultAlarmName = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int Delete = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Edit = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int Pause = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int Reset = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int Save = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int Start = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070007
			public const int EditorTimerLabelText = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int EditorTimerText = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int KeyPadRowStyle = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int KeyPadStyle = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int KeyPadStyleText = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int OldKeyPadStyleText = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int TimerAlarmNameText = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int TimerText = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
